Revert "Add spm test script"
This reverts commit 791fa6380d1fffc355b4ae52b0344363e3347ec5.

diff --git a/.github/workflows/performance.yml b/.github/workflows/performance.yml
--- a/.github/workflows/performance.yml
+++ b/.github/workflows/performance.yml
@@ -51,21 +51,67 @@ jobs:
           SAMPLE: Performance
       - name: Build and Test SwiftUI iOS
         run: |
-          ./scripts/test_spm.sh
+          set -io pipefail
+          EXIT_STATUS=0
+          source scripts/check_secrets.sh
+          cd performance/SwiftUIPerformanceQuickstart/PerformanceExample
+          if [[ "$have_secrets" == true ]]; then
+            (xcodebuild \
+              -project "$PATH" \
+              -scheme "${SAMPLE}Example (${OS})" \
+              -sdk "${SDK}simulator" \
+              -destination "platform=${OS} Simulator,name=${DEVICE}" \
+              build \
+              test \
+              | xcpretty) || EXIT_STATUS=$?
+          else
+            (xcodebuild \
+              -project "$PATH" \
+              -scheme "${SAMPLE}Example (${OS})" \
+              -sdk "${SDK}simulator" \
+              -destination "platform=${OS} Simulator,name=${DEVICE}" \
+              build \
+              | xcpretty) || EXIT_STATUS=$?
+            echo "Missing secrets: tests did not run."
+          fi
+          exit $EXIT_STATUS
         env:
           SAMPLE: Performance
-          PATH: performance/SwiftUIPerformanceQuickstart/PerformanceExample
+          PATH: PerformanceExample.xcodeproj
           OS: iOS
-          PLATFORM: iphone
+          SDK: iphone
           DEVICE: iPhone 11
           secrets_passphrase: ${{ secrets.GHASECRETSGPGPASSPHRASE1 }}
       - name: Build and Test SwiftUI tvOS
         run: |
-          ./scripts/test_spm.sh
+          set -io pipefail
+          EXIT_STATUS=0
+          source scripts/check_secrets.sh
+          cd performance/SwiftUIPerformanceQuickstart/PerformanceExample
+          if [[ "$have_secrets" == true ]]; then
+            (xcodebuild \
+              -project "$PATH" \
+              -scheme "${SAMPLE}Example (${OS})" \
+              -sdk "${SDK}simulator" \
+              -destination "platform=${OS} Simulator,name=${DEVICE}" \
+              build \
+              test \
+              | xcpretty) || EXIT_STATUS=$?
+          else
+            (xcodebuild \
+              -project "$PATH" \
+              -scheme "${SAMPLE}Example (${OS})" \
+              -sdk "${SDK}simulator" \
+              -destination "platform=${OS} Simulator,name=${DEVICE}" \
+              build \
+              | xcpretty) || EXIT_STATUS=$?
+            echo "Missing secrets: tests did not run."
+          fi
+          exit $EXIT_STATUS
         env:
           SAMPLE: Performance
-          PATH: performance/SwiftUIPerformanceQuickstart/PerformanceExample
+          PATH: PerformanceExample.xcodeproj
           OS: tvOS
-          PLATFORM: appletv
+          SDK: appletv
           DEVICE: Apple TV
           secrets_passphrase: ${{ secrets.GHASECRETSGPGPASSPHRASE1 }}
